name: Build HardwareMonitor Plugin

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # ================== 新增的调试步骤 ==================
      # 这个步骤会列出当前工作目录下的所有文件和文件夹
      # 让我们能准确地看到 .vcxproj 文件的位置
      - name: List files for debugging
        run: ls -Recurse
        shell: powershell
      # =====================================================

      - name: Build the HardwareMonitor project
        # 我们暂时保持这个路径，等待调试输出结果来确认或修正它
        run: msbuild HardwareMonitor/HardwareMonitor/HardwareMonitor.vcxproj /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HardwareMonitor-Plugin
          # 这个路径也可能需要根据调试结果来修正
          path: HardwareMonitor/HardwareMonitor/x64/Release/HardwareMonitor.dll
